#!/bin/bash

export GIT_WORK_TREE=$HOME
export GIT_DIR=$HOME/.config/chargepoint/.dot-files.git

mkdir -p $HOME/.config/chargepoint

git init
git remote add origin git@github.com:ChargePoint/emb-eu-dotiles.git
git fetch
git checkout main


export GIT_WORK_TREE=/
export GIT_DIR=$HOME/.config/chargepoint/.root.dot-files.git

sudo -E git init
sudo -E git remote add origin git@github.com:ChargePoint/emb-eu-dotiles.git
sudo -E git fetch
sudo -E git checkout labbox/main

