name: Generate artifacts on PR
#
# If PR is labeled with "Build" and you are a member of "Release manager" team it will start (additional security feature)
#

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, labeled]

concurrency:
  group: pipeline-pr-${{github.event.pull_request.number}}
  cancel-in-progress: true

run-name: 'PR Build All from ${{ github.head_ref }} of sha ${{ github.sha }}'

jobs:
  build:
    name: 'Build rockpi-4cplus'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          ./cp-build.sh
          mkdir downloads
          cp output/images/*.img.xz downloads

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads